name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: DockerHub Authentication
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      - name: "Docker image build"
        uses: docker/build-push-action@5.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            kadymo/kube-news:v1
            kadymo/kube-news:latest
